import { Providers } from "./providers";
import { auth } from "./api/auth/[...nextauth]/route";
import { SignIn, SignOut } from "./auth-components";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div>
            <aside className="fixed top-0 left-0 h-screen w-64 bg-gray-100 p-6 dark:bg-gray-900 flex flex-col justify-between">
              <div>
                <h2 className="text-xl font-semibold">Personal Agent</h2>
                <nav className="mt-8">
                  <ul className="space-y-4">
                    <li>
                      <Link
                        href="/"
                        className="text-gray-700 hover:text-black dark:text-gray-300 dark:hover:text-white"
                      >
                        Home
                      </Link>
                    </li>
                    <li>
                      <Link
                        href="/inbox"
                        className="text-gray-700 hover:text-black dark:text-gray-300 dark:hover:text-white"
                      >
                        Inbox Agent
                      </Link>
                    </li>
                  </ul>
                </nav>
              </div>
              <div>
                {session?.user ? (
                  <div className="flex items-center space-x-4 hover:bg-gray-200 p-2 rounded-full cursor-pointer">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={
                        session.user.image ??
                        "https://source.boringavatars.com/marble/120"
                      }
                      alt={session.user.name ?? ""}
                      className="h-10 w-10 rounded-full"
                    />
                    <div className="flex-1">
                      <p className="font-semibold">{session.user.name}</p>
                      <SignOut />
                    </div>
                  </div>
                ) : (
                  <SignIn />
                )}
              </div>
            </aside>
            <main className="ml-64 flex-1 p-10">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
